chef_versions = [
  '12.6.0',
  '12.7.2',
  '12.8.1',
  '12.9.38',
  '12.10.24',
  '12.11.18',
  '12.12.13',
  '12.13.37',
  '12.14.89',
  '12.15.19',
  '12.16.42',
  '12.17.44',
  '12.18.31',
  '12.19.36'
]
chef_versions.each do |version|
  appraise "chef_#{version}" do
    gem 'chef', version
    if !! RUBY_PLATFORM =~ /mswin|mingw|windows/
      gem 'ffi'
      gem 'ruby-wmi'
      gem 'win32-service'
    end
  end
end
