chef_versions = [
  "13.12.3",
  "14.10.9",
]
chef_versions.each do |version|
  appraise "chef_#{version}" do
    gem "chef", version
    if !! RUBY_PLATFORM =~ /mswin|mingw|windows/
      gem "ffi"
      gem "ruby-wmi"
      gem "win32-service"
    end
  end
end
