chef_versions = [
  "14.14.29",
  "15.4.45",
]
chef_versions.each do |version|
  appraise "chef_#{version}" do
    gem "chef", version
    if !! RUBY_PLATFORM =~ /mswin|mingw|windows/
      gem "ffi"
      gem "ruby-wmi"
      gem "win32-service"
    end
  end
end
