require "spec_helper"

describe "FC069" do
  context "with a cookbook with a metadata file that specifies a license generated by knife cookbook create" do
    metadata_file "license 'Apache 2.0'"
    it { is_expected.to violate_rule("FC069") }
  end

  context "with a cookbook with a metadata file that specifies a license generated by chef generate cookbook" do
    metadata_file "license 'apache_2'"
    it { is_expected.to violate_rule("FC069") }
  end

  context "with a cookbook with a metadata file that specifies a valid SPDX license" do
    metadata_file "license 'Apache-2.0'"
    it { is_expected.to_not violate_rule("FC069") }
  end
end
